import { StyleSheet } from "react-native";


export const styles = StyleSheet.create({
    HeaderText: {
      fontFamily: "Roboto-Bold",
      fontStyle: "normal",
      textAlign: "center",
      fontWeight: 500,
      fontSize: 17,
      lineHeight: 22,
      letterSpacing: -0.408,
    },
    TextH2: {
      fontFamily: "Roboto-Bold",
      fontStyle: "normal",
      fontSize: 16,
      fontWeight: 500,
      lineHeight: 19,
      color: "#212121",
    },
    RobotoBold: {
      fontFamily: "Roboto-Bold",
      fontStyle: "normal",
      fontSize: 30,
      fontWeight: 500,
      lineHeight: 35,
      color: "#212121",
      textAlign: "center",
      letterSpacing: 0.01,
    },
    RobotoRegular: {
      fontFamily: "Roboto-Regular",
      fontStyle: "normal",
      textAlign: "center",
      fontSize: 16,
      fontWeight: 400,
      lineHeight: 19,
    },
    RobotoMediumName: {
      fontFamily: "Roboto-Medium",
      fontStyle: "normal",
      fontWeight: 700,
      fontSize: 13,
      lineHeight: 15,
    },
    RobotoMediumEmail: {
      fontFamily: "Roboto-Regular",
      fontStyle: "normal",
      textAlign: "center",
      fontWeight: 400,
      fontSize: 11,
      lineHeight: 13,
    },
    CommentText: {
      fontFamily: "Roboto-Regular",
      paddingRight: 16,
      paddingLeft: 16,
      paddingTop: 16,
      fontSize: 13,
      fontWeight: 400,
      lineHeight: 18,
    },
    CommentData: {
      fontFamily: "Roboto-Regular",
      color: "#BDBDBD",
      width: 299,
      textAlign: "right",
      marginTop: 8,
      fontSize: 10,
      fontWeight: 400,
      lineHeight: 12,
      paddingLeft: 16,
      paddingRight: 16,
      paddingBottom: 16,
    },
  });
  